-- 模特 / 作者合作申请（前台用户自助提交，后台审核录入）
-- 幂等：CREATE TABLE IF NOT EXISTS，重复执行安全
CREATE TABLE IF NOT EXISTS `applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` enum('model','author') NOT NULL COMMENT '申请类型：model=模特申请，author=作者合作申请',
  `user_id` int(11) NOT NULL COMMENT '申请用户',
  `status` enum('pending','contacted','approved','rejected') DEFAULT 'pending' COMMENT '待处理/已联系/已通过/已驳回',
  `nickname` varchar(100) NOT NULL COMMENT '昵称/艺名',
  `gender` enum('男','女','保密') DEFAULT '保密',
  `age` tinyint(3) UNSIGNED DEFAULT NULL,
  `height` decimal(5,1) DEFAULT NULL COMMENT '身高 cm',
  `weight` decimal(4,1) DEFAULT NULL COMMENT '体重 kg',
  `measurements` varchar(50) DEFAULT NULL COMMENT '三围',
  `city` varchar(100) DEFAULT NULL COMMENT '所在城市',
  `zodiac` varchar(20) DEFAULT NULL COMMENT '星座',
  `hobbies` text COMMENT '爱好（模特）',
  `style` varchar(50) DEFAULT NULL COMMENT '创作风格（作者）',
  `bio` text COMMENT '作者简介',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `qq` varchar(20) DEFAULT NULL,
  `weixin` varchar(100) DEFAULT NULL,
  `weibo` varchar(200) DEFAULT NULL,
  `xiaohongshu` varchar(200) DEFAULT NULL,
  `photos` text COMMENT '照片/作品图 JSON 数组（已落正式目录）',
  `admin_remark` text COMMENT '后台备注',
  `reject_reason` varchar(255) DEFAULT NULL COMMENT '驳回原因（展示给用户）',
  `model_id` int(11) DEFAULT NULL COMMENT '录入后关联 model id',
  `author_id` int(11) DEFAULT NULL COMMENT '录入后关联 author id',
  `reviewed_at` datetime DEFAULT NULL COMMENT '处理时间',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_type_status` (`type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
